# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
 # pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: check out the repository
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      - name: installing node 
        uses: actions/setup-node@v1 #for installing node and npm
        with:
          node-version: '12.16.3'

      # Runs a single command using the runners shell
      - name: installation
        run: npm install
      - name: installing angular
        run: npm install -g @angular/cli
      - name: building application
        run: ng build --prod --output-path=dist --base-href="https://gokulakannan94.github.io/market_price_stats/"

      # Runs a set of commands using the runners shell
      # puts the compiled app to gh-pages branch
      - name: publish
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
